apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: builder-image-argocd-application-set-
spec:
  serviceAccountName: tekton-triggers-sa
  pipelineRef:
    name: builder-image-argocd-application-set
  podTemplate:
    securityContext:
      fsGroup: 65532          
  params:
  - name: builder-image-argocd-application-set
    value: "harbor.35.212.92.161.nip.io/leidos/perl:5.36.2"
  - name: builder-image-argocd-application-set-repo-url
    value: "https://github.com/martinmlouis/echimp.git"
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  - name: git-credentials
    secret:
      secretName: secret-basic-auth
  - name: harbor-access-secret
    secret:
      secretName: harbor-access-secret            

