apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: builder-image-argocd-application-set-start
spec:
  description: |
    This pipeline clones a git repo, then echoes the README file to the stout.

  tasks:
  - name: run-builder-image-argocd-application-set
    taskRef:
      name: kubernetes-actions
    params:
    - name: script
      value: kubectl create  -f https://raw.githubusercontent.com/martinmlouis/leidos/refs/heads/main/demo/build-push-argocd-application-set-pipelinerun.yaml
