apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IuMzUuMjEyLjkyLjE2MS5uaXAuaW8iOiB7CgkJCSJhdXRoIjogImJXRnlkR2x1Ykc5MWNtUjFjM2RoYlhrNlFXUnRhVzVBTWpFeiIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  name: harbor-access-secret
type: kubernetes.io/dockerconfigjson
