apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: import-resources
spec:
  params:
    - name: path
      type: string
      description: location to push the built image to
  workspaces:
    - name: shared-data
  steps:
    - name: read
      image: alpine:latest
      script: |
        #!/usr/bin/env sh
        pwd
        ls -ltr $(workspaces.shared-data.path)
    - name: import-configs
      script: |
        #!/usr/bin/env sh
        pwd
        kubectl apply -f $(workspaces.shared-data.path)/demo/ -n default
      image: lachlanevenson/k8s-kubectl:latest

