apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  - name: git-credentials
    description: My basic-auth credentials
  - name: harbor-access-secret
    description: Credentials to use to push to harbor registry.

  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: basic-auth
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url)
  - name: show-readme
    runAfter: ["fetch-source"]
    taskRef:
      name: show-readme
    workspaces:
    - name: source
      workspace: shared-data
  - name: show-readme-github
    runAfter: ["fetch-source"]
    taskRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/martinmlouis/leidos.git
        - name: pathInRepo
          value: demo/show-readme.yaml
    workspaces:
    - name: basic-auth
      workspace: git-credentials
    - name: source
      workspace: shared-data
  - name: import-resources
    runAfter: ["fetch-source"]
    taskRef:
      name: import-resources
    workspaces:
    - name: shared-data
      workspace: shared-data
    params:
    - name: path 
      value: "demo"
         
  - name: kaniko-build-push-harbor
    runAfter: ["import-resources"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: harbor-access-secret
    params:
    - name: IMAGE
      value: "harbor.35.212.92.161.nip.io/leidos/argocd:latest"
    - name: DOCKERFILE
      value: "builds/argocd-Dockerfile"
    - name: CONTEXT
      value: "builds/"
    - name: EXTRA_ARGS
      value: 
        - --skip-tls-verify
        - --cleanup
        - --insecure
        - --verbosity=trace
