apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-trigger
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push')"
        - name: "overlays"
          value:
            - key: extensions.truncated_sha
              expression: "body.head_commit.id"
            - key: extensions.repo-url
              expression: "body.repository.url"
            - key: extensions.changedfiles
              expression: "body.head_commit.added"
  bindings:
  - ref: github-triggerbinding
  template:
    ref: github-triggertemplate
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-remote-trigger
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push')"
        - name: "overlays"
          value:
            - key: extensions.truncated_sha
              expression: "body.head_commit.id"
            - key: extensions.repo-url
              expression: "body.repository.url"
            - key: extensions.changedfiles
              expression: "body.head_commit.added"
  bindings:
  - ref: github-remote-triggerbinding
  template:
    ref: github-remote-triggertemplate
