apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-trigger
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'pull_request')"
        - name: "overlays"
          value:
            - key: extensions.truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
    - ref:
        name: "github"
      params:
        - name: "eventTypes"
          value: ["pull_request", "push"]
        - name: "addChangedFiles"
          value:
            enabled: true            
  bindings:
  - ref: github-triggerbinding
  template:
    ref: github-triggertemplate
