apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-triggertemplate
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: main
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
    default: text/plain
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: demo-pipeline-run-
    spec:
      pipelineRef:
        name: clone-read
      podTemplate:
        securityContext:
          fsGroup: 65532          
      params:
      - name: message
        value: $(tt.params.message)
      - name: contenttype
        value: $(tt.params.contenttype)
      - name: git-revision
        value: $(tt.params.gitrevision)
      - name: repo-url
        value: $(tt.params.gitrepositoryurl)
      workspaces:
      - name: shared-data
        emptyDir: {}
      - name: git-credentials
        secret:
          secretName: secret-basic-auth
