apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-triggertemplate
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: main
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
    default: text/plain
  - name: repo-url
    description: The git repository url
  - name: branch
    description: The git repository branch      
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: demo-pipeline-run-
    spec:
      serviceAccountName: tekton-triggers-sa
      pipelineRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/martinmlouis/leidos.git
        - name: revision
          value: main
        - name: pathInRepo
          value: demo/pipeline.yaml
        - name: branch
          value: $(tt.params.branch)            
      podTemplate:
        securityContext:
          fsGroup: 65532          
      params:
      - name: message
        value: $(tt.params.message)
      - name: contenttype
        value: $(tt.params.contenttype)
      - name: git-revision
        value: $(tt.params.gitrevision)
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: builder-image-argocd-application-set
        value: "harbor.35.212.92.161.nip.io/leidos/perl:5.36.2"
      - name: builder-image-argocd-application-set-repo-url
        value: "https://github.com/martinmlouis/echimp.git"
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

      - name: git-credentials
        secret:
          secretName: secret-basic-auth
      - name: harbor-access-secret
        secret:
          secretName: harbor-access-secret            
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-remote-triggertemplate
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: main
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
    default: text/plain
  - name: repo-url
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: demo-remote-pipeline-run-
    spec:
      serviceAccountName: tekton-triggers-sa
      pipelineRef:
        name: clone-read
      podTemplate:
        securityContext:
          fsGroup: 65532          
      params:
      - name: message
        value: $(tt.params.message)
      - name: contenttype
        value: $(tt.params.contenttype)
      - name: git-revision
        value: $(tt.params.gitrevision)
      - name: repo-url
        value: $(tt.params.repo-url)
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

      - name: git-credentials
        secret:
          secretName: secret-basic-auth
      - name: harbor-access-secret
        secret:
          secretName: harbor-access-secret            
