apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-triggerbinding
spec:
  params:
    - name: changedfiles
      value: "$(body.head_commit.added)"
    - name: repo-url
      value: "$(body.repository.url)"
    - name: extensions.truncated_sha
      value: "$(body.head_commit.id)"
---        
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-remote-triggerbinding
spec:
  params:
    - name: changedfiles
      value: "$(body.head_commit.added)"
    - name: repo-url
      value: "$(body.repository.url)"
    - name: extensions.truncated_sha
      value: "$(body.head_commit.id)"
---        
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-remote-triggerbinding-sync
spec:
  params:
    - name: changedfiles
      value: "$(body.head_commit.added)"
    - name: repo-url
      value: "$(body.repository.url)"
    - name: extensions.truncated_sha
      value: "$(body.head_commit.id)"
